TARGET_VELOCITY: 1.0
VELOCITY_RESOLUTION: 0.01
YAWRATE_RESOLUTION: 0.01
PREDICT_TIME: 3.0
HZ: 10

TO_GOAL_COST_GAIN: 0.5
SPEED_COST_GAIN: 1.0
OBSTACLE_COST_GAIN: 1.0 #2.0
HEADING_COST_GAIN: 0.5

ANGLE_RESOLUTION: 0.0087
MAX_DIST: 2.0
GOAL_THRESHOLD: 1.0
TURN_DIRECTION_THRESHOLD: 0.2

LENGTH_ROBOT: 0.7
WIDTH_ROBOT: 0.8
