VELOCITY_RESOLUTION: 0.01
YAWRATE_RESOLUTION: 0.01
PREDICT_TIME: 2.0
HZ: 10

TO_GOAL_COST_GAIN: 0.8 # 0.5
SPEED_COST_GAIN: 0.2
OBSTACLE_COST_GAIN: 1.0 #2.0
HEADING_COST_GAIN: 0.5 #0.5

GOAL_THRESHOLD: 0.5
GOAL_X: 4.0
GOAL_Y: -2.0
TURN_DIRECTION_THRESHOLD: 0.2

LENGTH_ROBOT: 0.2
WIDTH_ROBOT: 0.8
